In [ ]:
Assignment No.03
Name:-Atharv Anil Jadhav
Roll No:-13207

In [2]:
import pandas as pd
df = pd.read_csv("C:/Users/athra/Downloads/Mall_Customers.csv")
df.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [3]:
df.mean(numeric_only=True)

CustomerID                100.50
Age                        38.85
Annual Income (k$)         60.56
Spending Score (1-100)     50.20
dtype: float64

In [4]:
df.median(numeric_only=True)

CustomerID                100.5
Age                        36.0
Annual Income (k$)         61.5
Spending Score (1-100)     50.0
dtype: float64

In [5]:
df.mode()

     CustomerID   Genre   Age  Annual Income (k$)  Spending Score (1-100)
0             1  Female  32.0                54.0                    42.0
1             2     NaN   NaN                78.0                     NaN
2             3     NaN   NaN                 NaN                     NaN
3             4     NaN   NaN                 NaN                     NaN
4             5     NaN   NaN                 NaN                     NaN
..          ...     ...   ...                 ...                     ...
195         196     NaN   NaN                 NaN                     NaN
196         197     NaN   NaN                 NaN                     NaN
197         198     NaN   NaN                 NaN                     NaN
198         199     NaN   NaN                 NaN                     NaN
199         200     NaN   NaN                 NaN                     NaN

[200 rows x 5 columns]

In [6]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [7]:
df.std(numeric_only=True)

CustomerID                57.879185
Age                       13.969007
Annual Income (k$)        26.264721
Spending Score (1-100)    25.823522
dtype: float64

In [8]:

df.min(numeric_only=True)

CustomerID                 1
Age                       18
Annual Income (k$)        15
Spending Score (1-100)     1
dtype: int64

In [9]:
df.groupby("Genre")["Age"].mean()

Genre
Female    38.098214
Male      39.806818
Name: Age, dtype: float64

In [10]:
df.loc[:,'Age'].mean()

np.float64(38.85)

In [11]:
df.mean(axis=1, numeric_only=True)[0:4]

0    18.50
1    29.75
2    11.25
3    30.00
dtype: float64

In [13]:
df.loc[:,'Age'].max(skipna = False)

np.int64(70)

In [14]:
df.std(numeric_only=True)

CustomerID                57.879185
Age                       13.969007
Annual Income (k$)        26.264721
Spending Score (1-100)    25.823522
dtype: float64

In [15]:
df.loc[:,'Age'].std()

13.969007331558883

In [16]:
df.std(axis=1,numeric_only=True)[0:4]

0    15.695010
1    35.074920
2     8.057088
3    32.300671
dtype: float64

In [17]:
df.groupby(['Genre'])['Age'].mean()

Genre
Female    38.098214
Male      39.806818
Name: Age, dtype: float64

In [ ]:

df_u = df.rename(columns={'Annual Income (k$)': 'Income'}, inplace=False)